### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by DutchUser** [netherfoam/MaxBans#30]
Hey, I have maybay an good idea voor a command. That if somebody do /banlist
That there stand ALL banned players like..
Banned Players
<Player/IP> <PlayerBanner>
'VocalWolf' Banned By 'JustGotFired'

Greetz. DutchUser
PS: Use-ing Google Translate

**Comment by iversenMC** [comment]
Use History of MYSQL for that, searching for the player, or simply doing /checkban.
I don't really see the need for this feature.

Also, sorry for the late answer. I was just added as a maintainer today.
