### ISSUE TITLE
Bug or...

### ISSUE THREAD

**Issue by DutchUser** [netherfoam/MaxBans#32]
Hello after using the MaxBans MaxBans 2.5 - Fixes (1.8, 1.8.1)
i got few issue's

First. You say that version(s) support UUID but why got my old names then other UUID then what i have now. So first i named, polski05 after that DutchGoldName and now VocalWolf and all 3 got diffrent UUID. So if people change there name they still can join. Because hes got an other UUID
NOTE: i not change them to check for the UUID support. 

two, When i use that version's i was not enable'd to tempban anymore oif i try i gor this
[TEMP-BAN] VocalWolf temp-ban aderikverraest voor N/A Je ban is verkort naar 1 week. Have Fun
So instead 7 days (or 1 weak) i got N/A and if look to /checkban hes not banned afterall

This was the reason to downgraden to MaxBans 2.3 for CB 1.7.2-R0.2

**Comment by iversenMC** [comment]
Offline or online server? On offline servers, UUID doesn't really do much since they're all fake (for offliner's and onliners')

Do you get any console errors?

**Comment by DutchUser** [comment]
I have an Online server. And no in console there are not any errors on that time

**Comment by iversenMC** [comment]
Hmh. Doesn't make sense to me. Joe will update MaxBans soon

**Comment by iversenMC** [comment]
Hmh. Doesn't make sense to me. Joe will update MaxBans soon. Will look into it

**Comment by DutchUser** [comment]
Oke. Thx
Then i close this ticket and look if its fix when the update'd version.
