### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by CzlowiekKuktas** [netherfoam/MaxBans#37]
MaxBans is causing lags.
http://scr.hu/1gy8/fdc6p
http://scr.hu/1gy8/ltea9

**Comment by iversenMC** [comment]
No one else is experiensing that - nor do we on my server.... Sure it is maxbans problem all on its' own?

**Comment by CzlowiekKuktas** [comment]
You can see high timings, but I think the MySQL with maxbans was causing the lag, maxbans is not lagging now (I think).

**Comment by iversenMC** [comment]
Good good.
