### ISSUE TITLE
Bungeecord?

### ISSUE THREAD

**Issue by Funnytom118** [netherfoam/MaxBans#47]
Does this work with bungeecord? Such as I add this to my proxy server, and add the permissions groups in the config.yml, with the permission nodes. Would this do it globally, or not?

**Comment by netherfoam** [comment]
You'd want to enable IP forwarding in spigot.yml (Have a google around for how to use the setting).

You'll also need to enable ban syncing, see:
http://dev.bukkit.org/bukkit-plugins/maxbans/pages/ban-syncing/

And
http://dev.bukkit.org/bukkit-plugins/maxbans/pages/sync-example-config/

**Comment by Funnytom118** [comment]
Okay thanks - Closed.
