### ISSUE TITLE
Bypassing a tempban/ban

### ISSUE THREAD

**Issue by keksbg** [netherfoam/MaxBans#74]
Recently in my server, I had banned a guy for asking for OP. He tried joining a couple of times, he couldn't.
But at one point while trying it said that he tried to join, but was banned but actually joined the server and went in the spawn!

**Comment by netherfoam** [comment]
Hi!

I don't maintain this plugin anymore, that's Fabio that does. Here's what I can think of though:
* If you tempbanned the guy, the ban could have expired
* If you're running an offline server, he could have changed his name to something similar (eg lbdBG to 1bdBG)
* One of your other plugins could be interfering

---

I'm presently working on MaxBansPlus over [here](https://www.spigotmc.org/resources/maxbans-plus.41392/) which is a rewrite of the plugin and changes a lot of nuances with it (Eg, it combines the tempban and ban command). It doesn't support a few of the things from the original MaxBans yet though:
* Range IP Bans
* Whitelisting players from bans
* Importing MaxBans mutes/warnings/bans
* DNS blacklist lookups

If this is a common issue for you, you could try the other one instead

**Comment by keksbg** [comment]
Thanks for your help. Closed.
Extra info: Was a temp ban, but he rejoined right after the ban.
